server:
  port: 8088


spring:
  devtools:
    livereload:
      port=35731:

  application:
    name: class-server

  #datasource:
  #  url: jdbc:mysql://localhost:3306/withuvideo?user=tang&password=973717287Thy&allowMultiQueries=true
  #  username: root
  #  password: 973717287thy
  #  driver-class-name: com.mysql.cj.jdbc.Driver

  # redis:
  #  host: 127.0.0.1
  #  port: 6379
  #  database: 2
    #password: 973717287Thy
  #  lettuce:
  #    pool:
  #      max-active: 5000  #最大连接数，负值表示没有限制，默认8
  #      max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
  #      max-idle: 5000     #最大空闲连接，默认8
  #      min-idle: 0     #最小空闲连接，默认0

  session:
    store-type: redis

